### ISSUE TITLE
Antijoins require distinct collection

### ISSUE THREAD

**Issue by ryzhyk** [ryzhyk/differential-datalog#128]
[Apparently](https://github.com/frankmcsherry/differential-dataflow/issues/121) the second argument of an antijoin in differential dataflow must be a distinct collection.

**Comment by frankmcsherry** [comment]
Quick comment, this is "as intended", but not very well documented (you would have to read `semijoin`s documentation and `antijoin`s implementation in terms of `semijoin`).

My sense is that it is good to have an operator that does not enforce distinctness, so that if you know that your input data are distinct, you can avoid a redundant computation. But, I think like with `semijoin` it may be that overloading the language here while cute just leads to confusion for folks who expect a relational, set-valued antijoin.

**Comment by frankmcsherry** [comment]
As mentioned over in the DD issue, one thing that could make sense is some very light tracking of "what relations must be distinct?" For example, the output of a distinct is distinct, a distinct collection that is filtered is still distinct, any collection subject to a map is not necessarily distinct, etc. The results of a join of distinct input relations will be distinct if no projection occurs, etc.
